version: '3.7'

services:

  frontend:
    container_name: frontend
    build: ./
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "8090:3006"
    expose:
      - 3006
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

